"""empty message

Revision ID: 243af2bb965d
Revises: 91b9e9fc9dc5
Create Date: 2021-12-24 21:37:57.143368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243af2bb965d'
down_revision = '91b9e9fc9dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profits')
    op.add_column('Sales', sa.Column('percentage_profit', sa.Integer(), nullable=True))
    op.drop_column('Sales', 'profit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sales', sa.Column('profit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Sales', 'percentage_profit')
    op.create_table('profits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='profits_pkey'),
    sa.UniqueConstraint('project_name', name='profits_project_name_key')
    )
    # ### end Alembic commands ###
