"""changed model of client

Revision ID: f9e35332de51
Revises: 5c4e67d95ab9
Create Date: 2021-11-25 00:11:32.630172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e35332de51'
down_revision = '5c4e67d95ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clients', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Clients', 'description')
    # ### end Alembic commands ###
